# Generated by Django 5.2.9 on 2025-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('tags_csv', models.TextField(blank=True, default='')),
            ],
        ),
    ]
